const char* indexHTML = 
"<!DOCTYPE html>"
"<html lang='en'>"
  "<head>"
    "<title>ESP32 Web Server</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1' />"
    "<link rel='icon' href='data:,' />"
    "<link rel='stylesheet' type='text/css' href='style.css' />"
  "</head>"
  "<form name='loginForm'>"
    "<h1>ESP32 Login V2</h1>"
    "<input name='userid' placeholder='User ID' />"
    "<input name='pwd' placeholder='Password' type='Password' />"
    "<input type='submit' onclick='check(this.form)' class='btn' value='Login' />"
  "</form>"
  "<script>"
    "function check(form) {"
      "if (form.userid.value == 'admin' && form.pwd.value == 'admin') {"
        "window.open('/serverIndex');"
      "} else {"
        "alert('Error Password or Username');"
      "}"
    "}"
  "</script>"
"</html>";

const char* serverIndexHTML =
"<!DOCTYPE html>"
"<html lang='en'>"
  "<head>"
  "<title>MFP #1 Web Server</title>"
    "<meta name='viewport' content='width=device-width, initial-scale=1' />"
    "<link rel='icon' href='data:,' />"
    "<link rel='stylesheet' type='text/css' href='style.css' />"
    "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
  "</head>"
  "<form name='resetForm'>"
    "<h1>Reset</h1>"
    "<input type='submit' onclick='check(this.form)' class='btn' value='Reset' />"
  "</form>"
  "<script>"
    "function check(form) {"
      "var xhr = new XMLHttpRequest();"
      "xhr.open('POST', '/reset', true);"
      "xhr.send();"
    "}"
    "function sub(obj) {"
      "var fileName = obj.value.split('\\\\');"
      "document.getElementById('file-input').innerHTML ="
        "'   ' + fileName[fileName.length - 1];"
    "}"
    "$('form').submit(function (e) {"
      "e.preventDefault();"
      "var form = $('#upload_form')[0];"
      "var data = new FormData(form);"
      "$.ajax({"
        "url: '/update',"
        "type: 'POST',"
        "data: data,"
        "contentType: false,"
        "processData: false,"
        "xhr: function () {"
          "var xhr = new window.XMLHttpRequest();"
          "xhr.upload.addEventListener("
            "'progress',"
            "function (evt) {"
              "if (evt.lengthComputable) {"
                "var per = evt.loaded / evt.total;"
                "$('#prg').html('progress: ' + Math.round(per * 100) + '%');"
                "$('#bar').css('width', Math.round(per * 100) + '%');"
              "}"
            "},"
            "false"
          ");"
          "return xhr;"
        "},"
        "success: function (d, s) {"
          "console.log('success!');"
        "},"
        "error: function (a, b, c) {},"
      "});"
    "});"
  "</script>"
"</html>";

const char* styleCSS =
"#file-input, input {"
    "width:100%;"
    "height:44px;"
    "border-radius:4px;"
    "margin:10px auto;"
    "font-size:15px;"
"}"
"input {"
    "background:#f1f1f1;border:0;"
    "padding:0 15px;"
"}"
"body{"
    "background:#3498db;"
    "font-family:sans-serif;"
    "font-size:14px;"
    "color:#777;"
"}"
"#file-input{"
    "padding:0;"
    "border:1px solid #ddd;"
    "line-height:44px;"
    "text-align:left;"
    "display:block;"
    "cursor:pointer;"
"}"
"#bar, #prgbar{"
    "background-color:#f1f1f1;"
    "border-radius:10px;"
"}"
"#bar{"
    "background-color:#3498db;"
    "width:0%;"
    "height:10px;"
"}"
"form{"
    "background:#fff;"
    "max-width:258px;"
    "margin:75px auto;"
    "padding:30px;"
    "border-radius:5px;"
    "text-align:center;"
"}"
".btn{"
    "background:#3498db;"
    "color:#fff;"
    "cursor:pointer;"
"}";
